### ISSUE TITLE
the name of species

### ISSUE THREAD

**Issue by Rimagination** [daijiang/rtrees#5]
Hello! My specific epithet and genus names are connected using spaces (e.g. Astronesthes micropogon), but in the file after building the tree, it becomes connected with “_” in each label (e.g. Astronesthe_micropogon). I would like to know if this connection can be changed? Because when I use it for some other analysis, this naming format causes a non-match between these species names and the species names in other data files.

**Comment by daijiang** [comment]
You should be able to do this with `gsub("_", " ", phy$tip.labels)`.

**Comment by Rimagination** [comment]
Thanks, this works.
